#!/usr/bin/env bash
#
# build-install-bundle.sh — produce the SELF-CONTAINED install-client.sh that the
# dashboard serves at GET /install-client.sh (and the release attaches).
#
# Why this exists
# ---------------
# The client installer is intentionally modular: client/install-client.sh is the
# orchestrator, and it sources its sub-steps from sibling files
# (client/lib/*.sh, client/install-baseline-tools.sh, client/distros/*.sh,
# client/self-test.sh). Those modules each have their own tests.
#
# But the documented bootstrap is a single download piped to a shell:
#
#   curl -fsSL https://<server>/install-client.sh | sudo bash -s -- …
#
# In that form there ARE no sibling files on the freshly-curled machine, and the
# script is read from stdin (so `${BASH_SOURCE[0]}` is unbound under `set -u`).
# The raw modular orchestrator therefore fails immediately with
#   "BASH_SOURCE[0]: unbound variable" / "lib/provision-agent-user.sh: No such file".
#
# This builder closes that gap WITHOUT collapsing the modular layout: it emits a
# single self-contained wrapper that base64-embeds the whole client install tree,
# extracts it to a private tempdir at runtime, and then runs the UNMODIFIED
# install-client.sh from that tempdir as a real file. Because the modules run from
# real files in a complete tree, every `${BASH_SOURCE[0]}`-relative source and the
# runtime distro-adapter dispatch resolve exactly as they do from a repo checkout.
#
# The wrapper needs only coreutils that ship with Mint/Ubuntu (mktemp, base64,
# mkdir, rm) plus bash. It is deterministic: same inputs -> byte-identical output
# (no timestamps, sorted file list), so image builds and releases are reproducible.
#
# License boundary (docs/licensing-analysis.md): pure bash packaging of this
# repo's own permissively-licensed scripts. No GPL code is embedded — the GPL
# tools are still installed from apt / upstream releases by the bundled
# install-baseline-tools.sh at run time, never vendored here.
#
# Usage:
#   client/build-install-bundle.sh [OUTPUT]
#       Write the self-contained bundle to OUTPUT (default: stdout).

set -euo pipefail

PCT_SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# The modular install tree, relative to client/. Order is irrelevant (each file
# is extracted before install-client.sh runs); kept sorted for a deterministic,
# reviewable bundle. install-client.sh is the entry point and is listed last for
# readability — the wrapper invokes it explicitly by name regardless of order.
PCT_BUNDLE_FILES=(
  "lib/pct-common.sh"
  "lib/pct-dispatch.sh"
  "lib/provision-agent-user.sh"
  "install-baseline-tools.sh"
  "self-test.sh"
)

# Every distro adapter (client/distros/<id>.sh) the runtime dispatch may source.
# Globbed so adding an adapter needs no change here. The .gitkeep is skipped.
for adapter in "${PCT_SRC_DIR}"/distros/*.sh; do
  [ -e "$adapter" ] || continue
  PCT_BUNDLE_FILES+=("distros/$(basename "$adapter")")
done

# install-client.sh is the entry point the wrapper runs.
PCT_BUNDLE_FILES+=("install-client.sh")

# Confirm every input exists before emitting anything, so a missing file is a
# hard build error rather than a half-written bundle.
for rel in "${PCT_BUNDLE_FILES[@]}"; do
  if [ ! -f "${PCT_SRC_DIR}/${rel}" ]; then
    printf 'build-install-bundle.sh: missing source file: %s\n' "${PCT_SRC_DIR}/${rel}" >&2
    exit 1
  fi
done

# Emit one extraction stanza per embedded file: a base64 heredoc piped into the
# extractor, which materialises it at its relative path under the tempdir.
emit_file_stanza() {
  local rel="$1"
  printf "pct_bundle_extract '%s' <<'PCT_BUNDLE_PAYLOAD_EOF'\n" "$rel"
  base64 <"${PCT_SRC_DIR}/${rel}"
  printf 'PCT_BUNDLE_PAYLOAD_EOF\n\n'
}

emit_bundle() {
  cat <<'PCT_BUNDLE_HEADER'
#!/usr/bin/env bash
#
# install-client.sh — SELF-CONTAINED CLIENT INSTALLER (generated artifact).
#
# DO NOT EDIT BY HAND. Generated by client/build-install-bundle.sh from the
# modular sources under client/ (install-client.sh + lib/ + distros/ +
# install-baseline-tools.sh + self-test.sh). Edit those, then rebuild.
#
# This wrapper exists so the installer works when downloaded and piped to a
# shell on a fresh machine that has none of the sibling modules:
#
#   curl -fsSL https://<server>/install-client.sh | sudo bash -s -- \
#       --server-url https://<server> \
#       --enrolment-token <token> \
#       --supervised-user <username>
#
# It unpacks the full install tree into a private tempdir and runs the real
# install-client.sh from there, so behaviour is identical to a repo checkout.

set -euo pipefail

# Private, per-run scratch dir for the unpacked install tree. mktemp gives it a
# 0700 owner-only mode; the trap removes it however the run ends.
PCT_BUNDLE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/pct-install.XXXXXX")"
trap 'rm -rf "$PCT_BUNDLE_DIR"' EXIT INT TERM

# Decode one embedded file (base64 on stdin) to its relative path under the
# tempdir, creating parent dirs as needed. Every embedded file is a shell
# script, so it is made executable — this is what lets the orchestrator's
# `[ -x self-test.sh ]` check find the bundled self-test, matching a repo run.
pct_bundle_extract() {
  local dest="${PCT_BUNDLE_DIR}/$1"
  mkdir -p "$(dirname "$dest")"
  base64 -d >"$dest"
  chmod +x "$dest"
}

PCT_BUNDLE_HEADER

  local rel
  for rel in "${PCT_BUNDLE_FILES[@]}"; do
    emit_file_stanza "$rel"
  done

  cat <<'PCT_BUNDLE_FOOTER'
# Run the real orchestrator from the unpacked tree, forwarding every argument.
# Its exit status becomes ours; the EXIT trap then cleans up the tempdir.
bash "${PCT_BUNDLE_DIR}/install-client.sh" "$@"
PCT_BUNDLE_FOOTER
}

if [ "$#" -ge 1 ] && [ "$1" != "-" ]; then
  mkdir -p "$(dirname "$1")"
  emit_bundle >"$1"
  chmod +x "$1"
else
  emit_bundle
fi
