/**
 * Assemble the live policy-push transport (#201, Phase 4) — the one place the
 * SSH facade, the `timekpra` client, the audit log (#85), the offline queue
 * (#84), and the dispatcher are wired together for production.
 *
 * `createPolicyPushTransport` decides at boot whether the live transport is
 * available: if the dashboard's SSH private key exists (generated by #39), it
 * builds the audited SSH `timekpra` client factory, the live executor, the
 * dispatcher, starts the offline-queue drainer (the "replay on next reachable
 * probe" half), and builds the client health prober (#81) over the same pooled
 * SSH transport. If the key is absent — dev, CI, tests, or a server before
 * first-run keygen — it falls back to the Phase-2 logging stub so the dashboard
 * still starts and CRUD still works (pushes are logged, not dispatched) and the
 * health prober is withheld, so `/api/clients/health` keeps degrading to
 * `unknown` reachability/components.
 *
 * The heavy collaborators (the SSH transport, the credential loader) are
 * injectable so this is unit-testable without a live client or real key files;
 * production uses the real defaults.
 *
 * License boundary: none touched — wires Drizzle + the SSH subprocess facade +
 * the `timekpra` CLI client. No GPL code is linked in-process and no GPL binary
 * is added to the image (`CLAUDE.md` → "License boundaries").
 */
import type { FastifyBaseLogger } from "fastify";

import type { Settings } from "../../config.js";
import type { PolicyDb } from "../../policy/db.js";
import { getClient } from "../../policy/repository.js";
import { AuditingTransport, DrizzleAuditSink, type AuditableTransport } from "../audit/index.js";
import { SshClientProber, type ClientProber } from "../health/index.js";
import {
  compositeExecutor,
  startOfflineQueueDrainer,
  type ReachabilityProbe,
} from "../queue/index.js";
import { SshError } from "../ssh/errors.js";
import {
  SshTransport,
  loadSshCredentials,
  targetFromClient,
  type PortForwardOptions,
  type PortForwardTarget,
  type SshCredentials,
  type SshTarget,
} from "../ssh/index.js";
import { createPolicyPushStub } from "../stub.js";
import type { PolicyPushStub } from "../stub.js";
import {
  adjustTimeToday,
  createTimeTodayExecutor,
  TIME_TODAY_KIND,
  type TimeTodayAdjustment,
  type TimeTodayResult,
} from "../time-today/index.js";
import { POLICY_PUSH_KIND } from "../queue/policy-push.js";
import { TimekprClient } from "../timekpr/index.js";
import { createPolicyPushDispatcher } from "./dispatcher.js";
import { createPolicyPushExecutor } from "./executor.js";
import { createLinuxPolicyRunner } from "./linux-runner.js";
import { createPlatformRunnerRegistry } from "./platform-runner.js";

/**
 * The SSH transport surface the bootstrap needs: the audited-command surface
 * (`exec`/`execChecked`/`execAndParse`, via {@link AuditableTransport}), the
 * loopback port-forward the health prober's ActivityWatch REST probe rides
 * (#323), plus the pooled-connection teardown. The real {@link SshTransport}
 * satisfies it; tests inject a fake.
 */
export interface BootstrapSshTransport extends AuditableTransport {
  withPortForward<T>(
    target: SshTarget,
    remote: PortForwardTarget,
    fn: (local: { host: string; port: number }) => Promise<T>,
    options?: PortForwardOptions,
  ): Promise<T>;
  disposeAll(): void;
}

/**
 * Applies a same-day "Add time today" adjustment (#257) over the live transport.
 * Awaitable (unlike the fire-and-forget dispatcher) so the admin route can
 * return a per-client result.
 */
export type TimeTodayAdjuster = (adjustment: TimeTodayAdjustment) => Promise<TimeTodayResult>;

/** A live policy-push transport: the dispatcher plus its teardown. */
export interface PolicyPushTransport {
  /** The dispatcher the policy routes push through. */
  readonly dispatcher: PolicyPushStub;
  /**
   * The "Add time today" adjuster (#257), present only when the live transport
   * is wired (SSH key exists). Absent in the logging fallback — the admin route
   * then reports the transport as unavailable rather than silently no-op'ing.
   */
  readonly adjustTimeToday?: TimeTodayAdjuster;
  /**
   * The live client health prober (#81), present only when the live transport
   * is wired (the SSH key exists). It runs `systemctl is-active` over the same
   * pooled SSH transport the `timekpra` pushes use; `buildApp` injects it into
   * the `/api/clients/health` routes so they report real reachability/component
   * health. Absent in the logging fallback (there is no SSH pool), where those
   * routes keep degrading to `unknown`.
   */
  readonly prober?: ClientProber;
  /** Stop the drainer and close pooled SSH connections (on `app.close()`). */
  dispose(): void;
}

/** Construction options for {@link createPolicyPushTransport}. */
export interface CreatePolicyPushTransportOptions {
  readonly settings: Settings;
  readonly db: PolicyDb;
  readonly log: FastifyBaseLogger;
  /** Credential loader; defaults to reading {@link Settings.sshPrivateKeyPath}. */
  readonly loadCredentials?: (privateKeyPath: string) => SshCredentials | null;
  /** SSH transport; defaults to a fresh pooled {@link SshTransport}. */
  readonly sshTransport?: BootstrapSshTransport;
  /** Clock for the executor's reference instant; overridable in tests. */
  readonly now?: () => Date;
}

/**
 * A cheap SSH reachability probe: run `true` on the client and treat the SSH
 * error taxonomy (unreachable / timed out) as "offline". Used by the drainer to
 * skip known-dead hosts before attempting a replay. Exported for unit testing;
 * production wires it inside {@link createPolicyPushTransport}.
 */
export function sshReachabilityProbe(
  db: PolicyDb,
  ssh: BootstrapSshTransport,
  credentials: SshCredentials,
): ReachabilityProbe {
  return async (clientId: number): Promise<boolean> => {
    const client = getClient(db, clientId);
    if (client === undefined) return false;
    try {
      await ssh.exec(targetFromClient(client, credentials), ["true"]);
      return true;
    } catch (error) {
      // The facade only rejects `exec` with the SSH taxonomy (unreachable /
      // timed out); anything else is an unexpected bug and must surface.
      if (error instanceof SshError) return false;
      throw error;
    }
  };
}

/**
 * Build the live policy-push transport, or the logging fallback when no SSH key
 * is available yet. Always returns a usable {@link PolicyPushTransport}.
 */
export function createPolicyPushTransport(
  options: CreatePolicyPushTransportOptions,
): PolicyPushTransport {
  const { settings, db, log } = options;
  const load = options.loadCredentials ?? loadSshCredentials;
  const credentials = load(settings.sshPrivateKeyPath);

  if (credentials === null) {
    log.warn(
      { component: "transport/policy-push", privateKeyPath: settings.sshPrivateKeyPath },
      "SSH private key not found; policy changes are logged, not pushed (run first-run keygen, #39)",
    );
    return {
      dispatcher: createPolicyPushStub(log),
      // Nothing to tear down: the fallback holds no SSH pool or drainer.
      dispose: (): void => undefined,
    };
  }

  const ssh = options.sshTransport ?? new SshTransport();
  const sink = new DrizzleAuditSink(db, log);
  const auditing = new AuditingTransport(ssh, sink);

  // The platform seam (#232): the live executor selects a runner per client by
  // `Client.platform`. Linux (`timekpra`-over-SSH) is the only registration
  // today — `Client.platform` defaults to `linux`, so every enrolled client
  // resolves here; a future `WindowsAgentRunner` is registered beside it without
  // touching the executor or the call sites.
  const linuxRunner = createLinuxPolicyRunner({
    log,
    buildClient: ({ client, username, userId, reason }) =>
      new TimekprClient(
        auditing.withContext({ clientId: client.id, userId, reason }),
        targetFromClient(client, credentials),
        username,
      ),
  });
  const registry = createPlatformRunnerRegistry([linuxRunner]);

  const executor = createPolicyPushExecutor({
    db,
    registry,
    defaultTz: settings.defaultTz,
    log,
    ...(options.now !== undefined ? { now: options.now } : {}),
  });

  const dispatcher = createPolicyPushDispatcher({ db, executor, log });
  const probe = sshReachabilityProbe(db, ssh, credentials);

  // The client health prober (#81) shares this same pooled SSH transport — but
  // its *un-audited* surface: a `systemctl is-active` liveness query and the
  // ActivityWatch `GET /api/0/info` probe over a loopback port-forward (#323)
  // are data, not admin commands, so they must not flood the audit log the way
  // the `timekpra` pushes (through `auditing`) deliberately do. buildApp injects
  // it into the /api/clients/health routes. The logger surfaces one structured
  // `warn` per failed probe with the classified failure cause (#353).
  const prober = new SshClientProber(ssh, credentials, { log });

  // The queued same-day-adjustment executor (#274): resolves an absolute
  // `--settimeleft` target on first reconnect and replays it idempotently. Runs
  // over the same audited `timekpra` client as the online lever below.
  const timeTodayExecutor = createTimeTodayExecutor({
    db,
    defaultTz: settings.defaultTz,
    ...(options.now !== undefined ? { now: options.now } : {}),
    buildClient: ({ client, username, userId }) =>
      new TimekprClient(
        auditing.withContext({
          clientId: client.id,
          userId,
          actor: "admin",
          reason: "time.adjusted",
        }),
        targetFromClient(client, credentials),
        username,
      ),
  });

  // The drainer replays both kinds: standing policy pushes and queued same-day
  // adjustments. The dispatcher above only ever pushes `policy.push`, so it
  // keeps driving that executor directly.
  const drainExecutor = compositeExecutor({
    [POLICY_PUSH_KIND]: executor,
    [TIME_TODAY_KIND]: timeTodayExecutor,
  });
  const drainer = startOfflineQueueDrainer({ db, probe, executor: drainExecutor, log });

  // The same-day "Add time today" lever (#257): a synchronous, audited
  // `--settimeleft` over the audited SSH `timekpra` client, attributed to the
  // admin. With the offline-queue variant enabled (#274), a client that is
  // unreachable at request time has the adjustment durably queued (resolved to
  // an idempotent absolute target on reconnect by `timeTodayExecutor` above)
  // rather than reported as a bare `unreachable`.
  const timeTodayAdjuster: TimeTodayAdjuster = (adjustment) =>
    adjustTimeToday(
      db,
      ({ client, username, userId }) =>
        new TimekprClient(
          auditing.withContext({
            clientId: client.id,
            userId,
            actor: "admin",
            reason: "time.adjusted",
          }),
          targetFromClient(client, credentials),
          username,
        ),
      adjustment,
      {
        defaultTz: settings.defaultTz,
        ...(options.now !== undefined ? { now: options.now } : {}),
      },
    );

  return {
    dispatcher,
    adjustTimeToday: timeTodayAdjuster,
    prober,
    dispose: (): void => {
      drainer.stop();
      ssh.disposeAll();
    },
  };
}
