/**
 * Assemble the live policy-push transport (#201, Phase 4) — the one place the
 * SSH facade, the `timekpra` client, the audit log (#85), the offline queue
 * (#84), and the dispatcher are wired together for production.
 *
 * `createPolicyPushTransport` decides at boot whether the live transport is
 * available: if the dashboard's SSH private key exists (generated by #39), it
 * builds the audited SSH `timekpra` client factory, the live executor, the
 * dispatcher, and starts the offline-queue drainer (the "replay on next
 * reachable probe" half). If the key is absent — dev, CI, tests, or a server
 * before first-run keygen — it falls back to the Phase-2 logging stub so the
 * dashboard still starts and CRUD still works (pushes are logged, not
 * dispatched), exactly as the health prober degrades pre-#39.
 *
 * The heavy collaborators (the SSH transport, the credential loader) are
 * injectable so this is unit-testable without a live client or real key files;
 * production uses the real defaults.
 *
 * License boundary: none touched — wires Drizzle + the SSH subprocess facade +
 * the `timekpra` CLI client. No GPL code is linked in-process and no GPL binary
 * is added to the image (`CLAUDE.md` → "License boundaries").
 */
import type { FastifyBaseLogger } from "fastify";

import type { Settings } from "../../config.js";
import type { PolicyDb } from "../../policy/db.js";
import { getClient } from "../../policy/repository.js";
import { AuditingTransport, DrizzleAuditSink, type AuditableTransport } from "../audit/index.js";
import { startOfflineQueueDrainer, type ReachabilityProbe } from "../queue/index.js";
import { SshError } from "../ssh/errors.js";
import {
  SshTransport,
  loadSshCredentials,
  targetFromClient,
  type SshCredentials,
} from "../ssh/index.js";
import { createPolicyPushStub } from "../stub.js";
import type { PolicyPushStub } from "../stub.js";
import { TimekprClient } from "../timekpr/index.js";
import { createPolicyPushDispatcher } from "./dispatcher.js";
import { createPolicyPushExecutor } from "./executor.js";

/**
 * The SSH transport surface the bootstrap needs: the audited-command surface
 * (`exec`/`execChecked`/`execAndParse`, via {@link AuditableTransport}) plus the
 * pooled-connection teardown. The real {@link SshTransport} satisfies it; tests
 * inject a fake.
 */
export interface BootstrapSshTransport extends AuditableTransport {
  disposeAll(): void;
}

/** A live policy-push transport: the dispatcher plus its teardown. */
export interface PolicyPushTransport {
  /** The dispatcher the policy routes push through. */
  readonly dispatcher: PolicyPushStub;
  /** Stop the drainer and close pooled SSH connections (on `app.close()`). */
  dispose(): void;
}

/** Construction options for {@link createPolicyPushTransport}. */
export interface CreatePolicyPushTransportOptions {
  readonly settings: Settings;
  readonly db: PolicyDb;
  readonly log: FastifyBaseLogger;
  /** Credential loader; defaults to reading {@link Settings.sshPrivateKeyPath}. */
  readonly loadCredentials?: (privateKeyPath: string) => SshCredentials | null;
  /** SSH transport; defaults to a fresh pooled {@link SshTransport}. */
  readonly sshTransport?: BootstrapSshTransport;
  /** Clock for the executor's reference instant; overridable in tests. */
  readonly now?: () => Date;
}

/**
 * A cheap SSH reachability probe: run `true` on the client and treat the SSH
 * error taxonomy (unreachable / timed out) as "offline". Used by the drainer to
 * skip known-dead hosts before attempting a replay. Exported for unit testing;
 * production wires it inside {@link createPolicyPushTransport}.
 */
export function sshReachabilityProbe(
  db: PolicyDb,
  ssh: BootstrapSshTransport,
  credentials: SshCredentials,
): ReachabilityProbe {
  return async (clientId: number): Promise<boolean> => {
    const client = getClient(db, clientId);
    if (client === undefined) return false;
    try {
      await ssh.exec(targetFromClient(client, credentials), ["true"]);
      return true;
    } catch (error) {
      // The facade only rejects `exec` with the SSH taxonomy (unreachable /
      // timed out); anything else is an unexpected bug and must surface.
      if (error instanceof SshError) return false;
      throw error;
    }
  };
}

/**
 * Build the live policy-push transport, or the logging fallback when no SSH key
 * is available yet. Always returns a usable {@link PolicyPushTransport}.
 */
export function createPolicyPushTransport(
  options: CreatePolicyPushTransportOptions,
): PolicyPushTransport {
  const { settings, db, log } = options;
  const load = options.loadCredentials ?? loadSshCredentials;
  const credentials = load(settings.sshPrivateKeyPath);

  if (credentials === null) {
    log.warn(
      { component: "transport/policy-push", privateKeyPath: settings.sshPrivateKeyPath },
      "SSH private key not found; policy changes are logged, not pushed (run first-run keygen, #39)",
    );
    return {
      dispatcher: createPolicyPushStub(log),
      // Nothing to tear down: the fallback holds no SSH pool or drainer.
      dispose: (): void => undefined,
    };
  }

  const ssh = options.sshTransport ?? new SshTransport();
  const sink = new DrizzleAuditSink(db, log);
  const auditing = new AuditingTransport(ssh, sink);

  const executor = createPolicyPushExecutor({
    db,
    defaultTz: settings.defaultTz,
    log,
    ...(options.now !== undefined ? { now: options.now } : {}),
    buildClient: ({ client, username, userId, reason }) =>
      new TimekprClient(
        auditing.withContext({ clientId: client.id, userId, reason }),
        targetFromClient(client, credentials),
        username,
      ),
  });

  const dispatcher = createPolicyPushDispatcher({ db, executor, log });
  const probe = sshReachabilityProbe(db, ssh, credentials);
  const drainer = startOfflineQueueDrainer({ db, probe, executor, log });

  return {
    dispatcher,
    dispose: (): void => {
      drainer.stop();
      ssh.disposeAll();
    },
  };
}
