/**
 * The `transport/ssh/` connection + exec facade.
 *
 * Every Phase-4+ remote action goes through here: open a key-authenticated
 * `ssh2` session to an enrolled {@link clients} box (as its `pct-agent`), run a
 * command, capture `{ stdout, stderr, code }`, and tear down cleanly. This is
 * the structural **license boundary** — the dashboard only ever *execs
 * subprocesses* over SSH, never linking GPL code (Timekpr-nExT, e2guardian) in
 * process. See `docs/licensing-analysis.md` and `docs/architecture.md` →
 * "Process boundaries".
 *
 * Arguments are always passed as a **vector** and shell-quoted
 * ({@link shellQuoteCommand}) into the single command string SSH's exec
 * request carries — never concatenated as raw text — so a value can never be
 * reinterpreted by the remote shell. Connections are pooled per target so the
 * timekpra commands (#83), the client health probe (#81), and the later AW
 * port-forward (Phase 5) reuse one session rather than reconnecting per call.
 *
 * Callers branch on the error taxonomy in `./errors.ts`: an
 * {@link SshUnreachableError} is the offline-queue's signal (#84), whereas an
 * {@link SshCommandError} means the box was reached and the *command* failed.
 */
import { createServer, type Server, type Socket } from "node:net";

import { Client } from "ssh2";
import type { ClientChannel, ConnectConfig } from "ssh2";
import type { ZodType } from "zod";

import type { clients } from "../../policy/schema.js";
import {
  SshCommandError,
  SshParseError,
  SshUnreachableError,
  type SshTargetRef,
} from "./errors.js";
import { ExecBuffer } from "./exec-buffer.js";
import { shellQuoteCommand } from "./shell-quote.js";

/** A `clients` row (the persisted enrolment record) the facade can target. */
type ClientRow = typeof clients.$inferSelect;

/** SSH credentials the dashboard authenticates with (the server's keypair). */
export interface SshCredentials {
  /** OpenSSH-format private key (key-based auth only — no passwords). */
  privateKey: string | Buffer;
  /** Passphrase, when the private key is encrypted. */
  passphrase?: string;
  /** TCP port; defaults to 22 when omitted. */
  port?: number;
}

/** A fully-resolved SSH connection descriptor. */
export interface SshTarget {
  /** Hostname or IP of the enrolled client. */
  host: string;
  /** TCP port; defaults to 22 when omitted. */
  port?: number;
  /** The `pct-agent` login the dashboard connects as. */
  username: string;
  /** OpenSSH-format private key for key-based auth. */
  privateKey: string | Buffer;
  /** Passphrase, when the private key is encrypted. */
  passphrase?: string;
}

/** The captured outcome of a remote command. */
export interface ExecResult {
  /** Decoded stdout (UTF-8). */
  stdout: string;
  /** Decoded stderr (UTF-8). */
  stderr: string;
  /** Process exit code, or `null` if the process was killed by a signal. */
  code: number | null;
  /** Terminating signal name, or `null` if the process exited normally. */
  signal: string | null;
}

/**
 * A remote endpoint on the enrolled client to forward a local port to.
 *
 * `host` defaults to loopback because the services we tunnel (notably
 * `aw-server`, #86) bind `127.0.0.1` on the client and must never be
 * network-exposed — the SSH tunnel is the *only* path to them.
 */
export interface PortForwardTarget {
  /** Remote host as resolved on the client. Defaults to `127.0.0.1`. */
  host?: string;
  /** Remote TCP port to forward to (e.g. `aw-server`'s `5600`). */
  port: number;
}

/** Per-invocation overrides for {@link SshTransport.withPortForward}. */
export interface PortForwardOptions {
  /**
   * Local TCP port to listen on. Defaults to `0` — an OS-assigned ephemeral
   * port, which is what callers want (the chosen port is handed to the
   * callback). Pinning a port is only useful in tests.
   */
  localPort?: number;
}

/** Per-invocation overrides for {@link SshTransport.exec}. */
export interface ExecOptions {
  /**
   * Abort the command after this many milliseconds (→ {@link SshExecTimeoutError}).
   * `0` (the default unless the transport sets one) disables the timeout.
   */
  timeoutMs?: number;
}

/** Construction-time defaults for an {@link SshTransport}. */
export interface SshTransportOptions {
  /** SSH handshake/ready timeout in ms (→ {@link SshUnreachableError}). Default 10000. */
  readyTimeoutMs?: number;
  /** Default per-exec timeout in ms; `0` disables. Default 30000. */
  execTimeoutMs?: number;
}

/**
 * Build an {@link SshTarget} from a persisted {@link clients} row plus the
 * dashboard's SSH credentials.
 *
 * Key material lives in the data volume (`/data/secrets/ssh/…`, generated by
 * the entrypoint — #39, Phase 4), not in the policy store, so it is injected
 * here rather than read from the row. The `clients` table carries no port, so
 * the credentials' port (or 22) is used.
 */
export function targetFromClient(
  client: Pick<ClientRow, "hostname" | "sshUser">,
  credentials: SshCredentials,
): SshTarget {
  const target: SshTarget = {
    host: client.hostname,
    username: client.sshUser,
    privateKey: credentials.privateKey,
  };
  if (credentials.port !== undefined) target.port = credentials.port;
  if (credentials.passphrase !== undefined) target.passphrase = credentials.passphrase;
  return target;
}

/** A pooled live connection plus the promise that resolves once it is ready. */
interface PooledConnection {
  client: Client;
  ready: Promise<Client>;
}

/** A target reduced to its pool key, human-readable ref, and connect config. */
interface ResolvedTarget {
  key: string;
  ref: SshTargetRef;
  connectConfig: ConnectConfig;
}

/** The only address a forwarded port ever binds — never network-exposed. */
const LOOPBACK_HOST = "127.0.0.1";

/**
 * SSH handshake/ready timeout — if the peer doesn't reach the ready state
 * within this window the host is treated as unreachable (the offline-queue's
 * retry signal), rather than the dashboard hanging on a dead box.
 */
const DEFAULT_READY_TIMEOUT_MS = 10_000;

/**
 * Default per-exec timeout. A facade orchestrating possibly-wedged remote
 * clients should never let a hung command block its caller forever, so exec is
 * time-boxed by default. `readyTimeout` only covers the handshake, not a
 * command that connected and then hung. Callers can override (or disable with
 * `0`) per invocation.
 */
const DEFAULT_EXEC_TIMEOUT_MS = 30_000;

/**
 * Pooled SSH transport. One instance is shared across the dashboard; it keeps
 * at most one live connection per `user@host:port` and lazily (re)connects on
 * first use after an eviction. Dispose connections with {@link dispose} /
 * {@link disposeAll} (e.g. on shutdown).
 */
export class SshTransport {
  readonly #readyTimeoutMs: number;
  readonly #execTimeoutMs: number;
  readonly #connections = new Map<string, PooledConnection>();

  constructor(options: SshTransportOptions = {}) {
    this.#readyTimeoutMs = options.readyTimeoutMs ?? DEFAULT_READY_TIMEOUT_MS;
    this.#execTimeoutMs = options.execTimeoutMs ?? DEFAULT_EXEC_TIMEOUT_MS;
  }

  /**
   * Run `argv` on the target and resolve with the captured streams and exit
   * status — **without** treating a non-zero exit as an error (the caller
   * inspects {@link ExecResult.code}). Rejects with {@link SshUnreachableError}
   * if the host can't be reached, or {@link SshExecTimeoutError} on timeout.
   */
  async exec(
    target: SshTarget,
    argv: readonly string[],
    options: ExecOptions = {},
  ): Promise<ExecResult> {
    return this.#exec(this.#resolve(target), argv, options);
  }

  /**
   * Like {@link exec}, but reject with {@link SshCommandError} when the command
   * exits non-zero (or is killed). Use this for commands whose success is
   * required — the timekpra setters (#83), the health probe (#81), …
   */
  async execChecked(
    target: SshTarget,
    argv: readonly string[],
    options: ExecOptions = {},
  ): Promise<ExecResult> {
    return this.#execChecked(this.#resolve(target), argv, options);
  }

  /**
   * Run a command that must succeed, then validate its stdout against `schema`
   * before the data crosses into typed code (`CLAUDE.md` → "Validate all
   * external input … subprocess stdout"). The schema receives the raw stdout
   * string, so callers supply tool-specific parsing via a zod `.transform`.
   * Rejects with {@link SshParseError} when stdout doesn't match.
   */
  async execAndParse<T>(
    target: SshTarget,
    argv: readonly string[],
    schema: ZodType<T>,
    options: ExecOptions = {},
  ): Promise<T> {
    const resolved = this.#resolve(target);
    const result = await this.#execChecked(resolved, argv, options);
    const parsed = schema.safeParse(result.stdout);
    if (!parsed.success) {
      throw new SshParseError(resolved.ref, argv, result.stdout, { cause: parsed.error });
    }
    return parsed.data;
  }

  /**
   * Open a **local port-forward** to `remote` on the target, run `fn` with the
   * loopback `{ host, port }` it can be reached at, then tear the forward down.
   *
   * A `127.0.0.1`-bound TCP listener is opened on an ephemeral local port;
   * each connection to it is forwarded over the pooled SSH session to
   * `remote` on the client (`ssh2`'s `forwardOut`). This is the inbound
   * transport window for the telemetry pull (#86): `fn` typically drives the
   * REST-only {@link ../activitywatch} client against
   * `http://127.0.0.1:<port>` to reach the client's `aw-server` — whose API is
   * unauthenticated and must never be network-exposed, hence loopback-only.
   *
   * The listener (and any in-flight sockets) are always closed when `fn`
   * settles, so a forward can't leak past its window. A connect failure
   * rejects with {@link SshUnreachableError} (the offline-queue's signal,
   * #84); a single forwarded connection that fails is dropped without sinking
   * the window. `fn`'s result is returned and its rejection propagates.
   */
  async withPortForward<T>(
    target: SshTarget,
    remote: PortForwardTarget,
    fn: (local: { host: string; port: number }) => Promise<T>,
    options: PortForwardOptions = {},
  ): Promise<T> {
    const resolved = this.#resolve(target);
    const client = await this.#connect(resolved);

    const remoteHost = remote.host ?? LOOPBACK_HOST;
    const openSockets = new Set<Socket>();
    const openChannels = new Set<ClientChannel>();

    const server = createServer((socket: Socket) => {
      openSockets.add(socket);
      socket.on("close", () => openSockets.delete(socket));
      // One broken forwarded connection must not take down the whole window.
      socket.on("error", () => socket.destroy());

      client.forwardOut(
        LOOPBACK_HOST,
        addressPort(server),
        remoteHost,
        remote.port,
        (err: Error | undefined, channel: ClientChannel) => {
          if (err !== undefined) {
            socket.destroy();
            return;
          }
          // Track the channel too: `socket.pipe(channel)` does not propagate a
          // socket `destroy()` to the SSH channel, so without this the channel
          // would linger half-open on the pooled connection across passes.
          openChannels.add(channel);
          channel.on("close", () => openChannels.delete(channel));
          channel.on("error", () => socket.destroy());
          socket.pipe(channel);
          channel.pipe(socket);
        },
      );
    });

    try {
      const port = await listenLoopback(server, options.localPort ?? 0);
      return await fn({ host: LOOPBACK_HOST, port });
    } finally {
      for (const socket of openSockets) socket.destroy();
      for (const channel of openChannels) channel.destroy();
      await closeServer(server);
    }
  }

  /** {@link execChecked} against an already-resolved target (resolve once). */
  async #execChecked(
    resolved: ResolvedTarget,
    argv: readonly string[],
    options: ExecOptions,
  ): Promise<ExecResult> {
    const result = await this.#exec(resolved, argv, options);
    if (result.code !== 0) {
      throw new SshCommandError(resolved.ref, argv, result);
    }
    return result;
  }

  /** {@link exec} against an already-resolved target (resolve once per call). */
  async #exec(
    resolved: ResolvedTarget,
    argv: readonly string[],
    options: ExecOptions,
  ): Promise<ExecResult> {
    const command = shellQuoteCommand(argv);
    const client = await this.#connect(resolved);
    const timeoutMs = options.timeoutMs ?? this.#execTimeoutMs;

    try {
      return await new ExecBuffer({ ref: resolved.ref, argv, timeoutMs }).run(client, command);
    } catch (error) {
      // A dead session — the exec request failed, or the channel dropped
      // mid-command — surfaces as SshUnreachableError; evict the (now-suspect)
      // pooled connection so the next call reconnects. A timeout leaves it
      // pooled: the host answered, only the command hung.
      if (error instanceof SshUnreachableError) this.#connections.delete(resolved.key);
      throw error;
    }
  }

  /** Close and forget the pooled connection to `target`, if any. */
  dispose(target: SshTarget): void {
    const { key } = this.#resolve(target);
    const pooled = this.#connections.get(key);
    if (pooled !== undefined) {
      this.#connections.delete(key);
      pooled.client.end();
    }
  }

  /** Close every pooled connection (e.g. on shutdown). */
  disposeAll(): void {
    for (const pooled of this.#connections.values()) {
      pooled.client.end();
    }
    this.#connections.clear();
  }

  /** Number of live pooled connections (diagnostics / tests). */
  get connectionCount(): number {
    return this.#connections.size;
  }

  /** Return the pooled connection for `resolved`, opening one if needed. */
  #connect(resolved: ResolvedTarget): Promise<Client> {
    const existing = this.#connections.get(resolved.key);
    if (existing !== undefined) return existing.ready;

    const client = new Client();
    const ready = new Promise<Client>((resolve, reject) => {
      let settled = false;
      client.once("ready", () => {
        settled = true;
        resolve(client);
      });
      // `on`, not `once`: some peers (e.g. a server that drops the TCP
      // connection before the SSH handshake) make `ssh2` emit `error` more
      // than once. A second `error` with no listener is an unhandled-error
      // crash, so absorb repeats here — the `settled` guard means only the
      // first rejects, and later ones just keep the (now-dead) connection
      // evicted.
      client.on("error", (err: Error) => {
        this.#connections.delete(resolved.key);
        if (!settled) {
          settled = true;
          reject(new SshUnreachableError(resolved.ref, { cause: err }));
        }
      });
      // A drop after the session was established evicts it so the next call
      // reconnects rather than reusing a dead handle.
      client.on("close", () => this.#connections.delete(resolved.key));
      client.connect(resolved.connectConfig);
    });

    // The caller awaits the returned promise, so a connect failure is handled
    // there. Attach a no-op rejection handler to the pooled copy as well so a
    // failure can never surface as an unhandledRejection if a future path
    // touches the pooled entry without awaiting `ready`.
    ready.catch(() => undefined);
    this.#connections.set(resolved.key, { client, ready });
    return ready;
  }

  /** Reduce a target to its pool key, error ref, and ssh2 connect config. */
  #resolve(target: SshTarget): ResolvedTarget {
    const port = target.port ?? 22;
    const connectConfig: ConnectConfig = {
      host: target.host,
      port,
      username: target.username,
      privateKey: target.privateKey,
      readyTimeout: this.#readyTimeoutMs,
    };
    if (target.passphrase !== undefined) connectConfig.passphrase = target.passphrase;
    return {
      key: `${target.username}@${target.host}:${port}`,
      ref: { host: target.host, port, username: target.username },
      connectConfig,
    };
  }
}

/** The bound TCP port of a listening server (0 before it is listening). */
function addressPort(server: Server): number {
  const address = server.address();
  return typeof address === "object" && address !== null ? address.port : 0;
}

/** Resolve once `server` is listening on loopback `port`, with its actual port. */
function listenLoopback(server: Server, port: number): Promise<number> {
  return new Promise<number>((resolve, reject) => {
    const onError = (err: Error): void => reject(err);
    server.once("error", onError);
    server.listen(port, LOOPBACK_HOST, () => {
      server.removeListener("error", onError);
      // Swallow late operational errors so a transient socket fault on the
      // loopback listener can't surface as an unhandled 'error' that crashes
      // the process; the forward is best-effort and its consumer reports
      // failures of its own.
      server.on("error", () => undefined);
      resolve(addressPort(server));
    });
  });
}

/** Close `server`, resolving once it has stopped accepting connections. */
function closeServer(server: Server): Promise<void> {
  return new Promise<void>((resolve) => {
    server.close(() => resolve());
  });
}
