#!/usr/bin/env bash
#
# provision-agent-user.sh — create the low-privilege `pct-agent` service
# account and its narrowly-scoped sudoers rule on a supervised client.
# (linux-parental-controls-toolkit, issue #78)
#
# `pct-agent` is the SSH principal the dashboard connects as. It is granted
# NOPASSWD sudo for EXACTLY the Timekpr-nExT admin CLI (`timekpra`) and nothing
# else: the Phase 4 transport's session-limit pushes and the Phase 8b bridge's
# `timekpra --kill-session` all go through that one binary. Privileged actions
# applied by Ansible (Phase 6, #90/#92) extend the sudoers surface via their
# OWN scoped drop-in when those playbooks land — we deliberately do NOT
# pre-grant broad root here. Least privilege is the bounded tamper-resistance
# posture (docs/client-install.md -> "Tamper resistance posture").
#
# Sourceable: the Phase-3 orchestrator install-client.sh (#76) does
#   source .../provision-agent-user.sh
#   pct_provision_agent_user --ssh-key /path/to/dashboard.pub
# and the functions below do the work. Also directly runnable for standalone
# use and testing. Idempotent: re-running reconciles rather than duplicates.
#
# Env overrides (defaults match a real Mint client; the test suite points them
# at a tmpdir so the logic runs unprivileged):
#   PCT_AGENT_USER     service account name              (default pct-agent)
#   PCT_SUDOERS_DIR    sudoers.d directory               (default /etc/sudoers.d)
#   PCT_TIMEKPRA_PATH  absolute path to the timekpra CLI (default /usr/bin/timekpra)
#   PCT_VISUDO         visudo binary used for validation (default visudo)

set -euo pipefail

PCT_AGENT_USER="${PCT_AGENT_USER:-pct-agent}"
PCT_SUDOERS_DIR="${PCT_SUDOERS_DIR:-/etc/sudoers.d}"
PCT_TIMEKPRA_PATH="${PCT_TIMEKPRA_PATH:-/usr/bin/timekpra}"
PCT_VISUDO="${PCT_VISUDO:-visudo}"

# sudoers ignores drop-in files whose names contain a '.' or '~', so keep this
# a plain token.
readonly PCT_SUDOERS_FILE_BASENAME="pct-agent"

log() { printf '[provision-agent-user] %s\n' "$*" >&2; }
die() {
  printf '[provision-agent-user] ERROR: %s\n' "$*" >&2
  exit 1
}

# Whether the service account already exists.
pct_agent_user_exists() {
  getent passwd "${PCT_AGENT_USER}" >/dev/null 2>&1
}

# pct-agent's home directory, per the passwd database.
pct_agent_home() {
  getent passwd "${PCT_AGENT_USER}" | cut -d: -f6
}

# Create the low-privilege system account (idempotent).
pct_create_agent_user() {
  if pct_agent_user_exists; then
    log "service account '${PCT_AGENT_USER}' already exists; leaving it unchanged"
    return 0
  fi
  log "creating system account '${PCT_AGENT_USER}'"
  # --system: no login/UID-range churn; --create-home: pct-agent needs a home
  # for ~/.ssh/authorized_keys; /bin/bash so the SSH 'exec' channel works.
  useradd --system --create-home --shell /bin/bash "${PCT_AGENT_USER}"
}

# Render the sudoers drop-in content to stdout.
pct_render_sudoers() {
  cat <<EOF
# Managed by linux-parental-controls-toolkit — pct-agent service account.
# Generated by client/lib/provision-agent-user.sh (issue #78).
# DO NOT EDIT BY HAND; re-running the installer reconciles this file.
#
# Least-privilege: pct-agent (the SSH principal the dashboard connects as) may
# run ONLY the Timekpr-nExT admin CLI as root, without a password. This covers
# the Phase 4 session-limit pushes and the Phase 8b bridge's
# 'timekpra --kill-session'. No general-purpose root is granted.
#
# Ansible-applied privileged actions (Phase 6, #90/#92) add their own scoped
# drop-in when those playbooks land — see docs/client-install.md.
${PCT_AGENT_USER} ALL=(root) NOPASSWD: ${PCT_TIMEKPRA_PATH}
EOF
}

# Install the scoped sudoers drop-in (idempotent, visudo-validated, atomic).
pct_install_sudoers() {
  local target content tmp
  target="${PCT_SUDOERS_DIR}/${PCT_SUDOERS_FILE_BASENAME}"
  content="$(pct_render_sudoers)"

  if [[ -f "${target}" ]] && [[ "$(cat "${target}")" == "${content}" ]]; then
    log "sudoers drop-in '${target}' already current"
    return 0
  fi

  mkdir -p "${PCT_SUDOERS_DIR}"
  tmp="$(mktemp)"
  printf '%s\n' "${content}" >"${tmp}"
  chmod 0440 "${tmp}"

  # Never install syntactically invalid sudoers — a bad file can lock out sudo.
  if ! "${PCT_VISUDO}" -cf "${tmp}" >/dev/null 2>&1; then
    rm -f "${tmp}"
    die "generated sudoers content failed '${PCT_VISUDO} -cf' validation; not installing"
  fi

  # Atomic replace, then lock down ownership/mode as sudoers requires (0440,
  # root:root). chown runs as root in production; the test suite stubs it.
  mv "${tmp}" "${target}"
  chmod 0440 "${target}"
  chown root:root "${target}"
  log "installed sudoers drop-in '${target}'"
}

# Authorize an SSH public key for pct-agent (idempotent, deduped).
pct_authorize_ssh_key() {
  local key home ssh_dir auth
  key="$1"
  home="$(pct_agent_home)"
  [[ -n "${home}" ]] || die "cannot determine home directory for '${PCT_AGENT_USER}'"

  ssh_dir="${home}/.ssh"
  auth="${ssh_dir}/authorized_keys"
  mkdir -p "${ssh_dir}"
  chmod 0700 "${ssh_dir}"
  touch "${auth}"
  chmod 0600 "${auth}"

  if grep -qxF -- "${key}" "${auth}" 2>/dev/null; then
    log "ssh key already authorized for '${PCT_AGENT_USER}'"
  else
    printf '%s\n' "${key}" >>"${auth}"
    log "authorized ssh key for '${PCT_AGENT_USER}'"
  fi

  # Own the tree as pct-agent; stubbed under test (can't chown unprivileged).
  chown -R "${PCT_AGENT_USER}:${PCT_AGENT_USER}" "${ssh_dir}"
}

pct_usage() {
  cat <<'EOF'
Usage: provision-agent-user.sh [--ssh-key <file> | --ssh-key-string <key>]

Creates the low-privilege pct-agent service account and its scoped sudoers
rule. Optionally authorizes a dashboard SSH public key for it.

  --ssh-key <file>          install the public key read from <file>
  --ssh-key-string <key>    install the public key given inline
  -h, --help                show this help

With no key argument the account + sudoers are provisioned and the
authorized_keys step is skipped (the orchestrator #76 fetches the dashboard
key via the one-time enrolment token #77 and passes it in).
EOF
}

# Provision everything: account, sudoers, and optionally the SSH key.
pct_provision_agent_user() {
  local ssh_key="" ssh_key_file=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --ssh-key-string)
        ssh_key="${2:-}"
        shift 2
        ;;
      --ssh-key)
        ssh_key_file="${2:-}"
        shift 2
        ;;
      -h | --help)
        pct_usage
        return 0
        ;;
      *)
        die "unknown argument: $1"
        ;;
    esac
  done

  pct_create_agent_user
  pct_install_sudoers

  if [[ -n "${ssh_key_file}" ]]; then
    [[ -r "${ssh_key_file}" ]] || die "ssh key file not readable: ${ssh_key_file}"
    ssh_key="$(cat "${ssh_key_file}")"
  fi

  if [[ -n "${ssh_key}" ]]; then
    pct_authorize_ssh_key "${ssh_key}"
  else
    log "no ssh public key provided; skipping authorized_keys"
  fi
}

# Run when executed directly; do nothing extra when sourced by the orchestrator.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  pct_provision_agent_user "$@"
fi
